### ISSUE TITLE
Error Container-init binary not found on the host

### ISSUE THREAD

**Issue by djarbz** [alvistack/ansible-role-podman#10]
When using the `--init` flag on podman run I get the following error.
`Error: container-init binary not found on the host: stat /usr/libexec/podman/catatonit: no such file or directory`

It looks like your repo installs catatonit into `/usr/bin/catatonit` rather than the expected `/usr/libexec/podman/catatonit`.

**Comment by hswong3i** [comment]
Debian sid install as `/usr/bin/catatonit`: https://debian.pkgs.org/sid/debian-main-amd64/catatonit_0.1.7-1_amd64.deb.html

openSUSE Tumbleweed as install as `/usr/bin/catatonit`: https://opensuse.pkgs.org/tumbleweed/opensuse-oss-x86_64/catatonit-0.1.7-1.4.x86_64.rpm.html

Only Fedora Rawhide install as `/usr/libexec/podman/catatonit`: https://fedora.pkgs.org/rawhide/fedora-x86_64/catatonit-0.1.7-7.fc37.x86_64.rpm.html

Personally my Docker image packaging will depends on my Ansible Role for catatonit and gosu, which normally expect it could find from PATH, which is also `/usr/bin/catatonit`, see https://github.com/alvistack/docker-ubuntu/blob/master/packer/docker-22.04/packer.json#L12

IMHO we should update our containers-common deb/rpm packaging, so set the default as `/usr/bin/catatonit` accordingly, see https://github.com/containers/common/blob/main/pkg/config/containers.conf#L149:
```
#init_path = "/usr/libexec/podman/catatonit"
```

Or even better, patch as https://github.com/containers/common/blob/main/pkg/config/containers.conf#L359-L367 (ok, https://github.com/containers/common/issues/1110 also have similar discussion):
```
#conmon_path = [
#  "/usr/libexec/podman/conmon",
#  "/usr/local/libexec/podman/conmon",
#  "/usr/local/lib/podman/conmon",
#  "/usr/bin/conmon",
#  "/usr/sbin/conmon",
#  "/usr/local/bin/conmon",
#  "/usr/local/sbin/conmon"
#]
```
Any idea?

**Comment by hswong3i** [comment]
I temporarily fix this by hard code the path for our package: https://github.com/alvistack/containers-common/commit/4629dfac44a9f5accbdbabe42ae6bab6342368e4#diff-f38944fdd6507cc37badbde5c66785bdebb77bd6fa2ea0674cd8117f89e95676R152

Reinstall the newly build containers-common could fix the problem.

**Comment by djarbz** [comment]
I get the following errors when trying to update:
```
Get:65 http://download.opensuse.org/repositories/home:/alvistack/Debian_11  containernetworking 100:1.1.2-1 [1,089 kB]
Err:65 http://download.opensuse.org/repositories/home:/alvistack/Debian_11  containernetworking 100:1.1.2-1
  File has unexpected size (1062836 != 1089332). Mirror sync in progress? [IP: 91.193.113.70 80]
  Hashes of expected file:
   - SHA256:e63073beafbf96af70c8a35d68468a5c2278615e95b095fb59babfdba550e7bb
   - SHA1:2fc2a946da71ca56e3a043f1c678c0d784a51d14 [weak]
   - MD5Sum:add9a16e7ea61037765b72b75bceb52b [weak]
   - Filesize:1089332 [weak]
Get:66 http://download.opensuse.org/repositories/home:/alvistack/Debian_11  containernetworking-plugins 100:1.1.1-1 [7,330 kB]
Err:66 http://download.opensuse.org/repositories/home:/alvistack/Debian_11  containernetworking-plugins 100:1.1.1-1
  File has unexpected size (7128344 != 7329992). Mirror sync in progress? [IP: 91.193.113.70 80]
  Hashes of expected file:
   - SHA256:c6bd58ce735fc64482af27aca1e4600ddfa152b758b09dd4231a21ea04f36e99
   - SHA1:26f0f3ab81928af94061d376d21f3a7fb5433fdb [weak]
   - MD5Sum:2af66aca391ca0469c9fa49f8a104b4f [weak]
   - Filesize:7329992 [weak]
E: Failed to fetch http://provo-mirror.opensuse.org/repositories/home:/alvistack/Debian_11/all/vim-common_8.2.5069-1_all.deb  File has unexpected size (71596 != 72100). Mirror sync in progress? [IP: 91.193.113.70 80]
   Hashes of expected file:
    - SHA256:be6cefffe402995ff7d049a46988e8b8c5875760c56d4ee89cbc0437c3f21721
    - SHA1:55f2ecb04bd475179030078a68107c5ba58ce81e [weak]
    - MD5Sum:59db4c2ae354d58469081f401d95aaab [weak]
    - Filesize:72100 [weak]
E: Failed to fetch http://provo-mirror.opensuse.org/repositories/home:/alvistack/Debian_11/amd64/containernetworking_1.1.2-1_amd64.deb  File has unexpected size (1062836 != 1089332). Mirror sync in progress? [IP: 91.193.113.70 80]
   Hashes of expected file:
    - SHA256:e63073beafbf96af70c8a35d68468a5c2278615e95b095fb59babfdba550e7bb
    - SHA1:2fc2a946da71ca56e3a043f1c678c0d784a51d14 [weak]
    - MD5Sum:add9a16e7ea61037765b72b75bceb52b [weak]
    - Filesize:1089332 [weak]
E: Failed to fetch http://provo-mirror.opensuse.org/repositories/home:/alvistack/Debian_11/amd64/containernetworking-plugins_1.1.1-1_amd64.deb  File has unexpected size (7128344 != 7329992). Mirror sync in progress? [IP: 91.193.113.70 80]
   Hashes of expected file:
    - SHA256:c6bd58ce735fc64482af27aca1e4600ddfa152b758b09dd4231a21ea04f36e99
    - SHA1:26f0f3ab81928af94061d376d21f3a7fb5433fdb [weak]
    - MD5Sum:2af66aca391ca0469c9fa49f8a104b4f [weak]
    - Filesize:7329992 [weak]
```

**Comment by hswong3i** [comment]
> I get the following errors when trying to update:

Because OBS repo getting update when new packages comes, you could check the status from https://build.opensuse.org/project/show/home:alvistack

Also don't trust those mirror site, use http://downloadcontent.opensuse.org instead.

**Comment by djarbz** [comment]
Yup, I was able to update now, I updated my Ansible Podman role to reference this URL for the repo as well.
Seems to be working.
