### ISSUE TITLE
ansible on localhost - Additional properties are not allowed ('pipelining', 'ssh_args' were unexpected)

### ISSUE THREAD

**Issue by lvnilesh** [alvistack/ansible-role-podman#12]
```
root@linux:~/.ansible/roles/podman# molecule converge -s default
CRITICAL Failed to validate /root/.ansible/roles/podman/molecule/default/molecule.yml

["Additional properties are not allowed ('pipelining', 'ssh_args' were unexpected)"]
```

The workaround is to delete three lines starting from https://github.com/alvistack/ansible-role-podman/blob/master/molecule/default/molecule.yml#L44

**Comment by hswong3i** [comment]
Please refer https://github.com/alvistack/ansible-role-podman/issues/13#issuecomment-1302965418 for some detail setup.

Moreover, these config is passing with our GitLab CI (see https://gitlab.com/alvistack/ansible-role-podman/-/jobs/3187525820), so it is most likely related to different setup ;-)
