### ISSUE TITLE
ansible.builtin.apt_key requires gpg

### ISSUE THREAD

**Issue by hmoffatt** [alvistack/ansible-role-podman#16]
`ansible.builtin.apt_key` requires gpg be installed, but it's not essential on Debian and hence may not be installed by default.

**Comment by hswong3i** [comment]
Somehow you are correct 👍 

In my case I build the Debian Vagrant Libvirt base box for my Ansible Role tests, by reusing these Ansible Roles during base box packaging.

With my self dogfooding I made gpg installed by default inside the base box, so we pass our own Ansible Role tests even didn't specify gpg precisely.

With my old bad days when working with generic/debian base boxes I do need to specify gpg in *each* of my Ansible Role, making its logic looks very bulky...

From my point of view, as a sysadmin working with our Debian box daily, soon we need this missing gpg for our daily operation, and we should already skillful enough for handling this missing package ;-)
