### ISSUE TITLE
Warning "dbus-launch": executable file not found in $PATH

### ISSUE THREAD

**Issue by akira25** [alvistack/ansible-role-podman#17]
after running the role on a fresh Debian11-system, we get this warning, when running the docker-hello-world container:

```sh
~$ podman run docker.io/library/hello-world
Trying to pull docker.io/library/hello-world:latest...
Getting image source signatures
Copying blob 2db29710123e done  
Copying config feb5d9fea6 done  
Writing manifest to image destination
Storing signatures

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/

WARN[0002] Failed to add pause process to systemd sandbox cgroup: exec: "dbus-launch": executable file not found in $PATH
```

This warning can be fixed easily by installing the debain-package `dbus-user-session`. After installing and login out and in again, the warning doesn't occur anymore.

Maybe this role should install that package too, when running on debain11.

**Comment by hswong3i** [comment]
Shouldn't it report to upstream podman repo, but not dirty workaround by a downstream DevOps Ansible Role? eg

- https://github.com/containers/podman/issues/9353

**Comment by hswong3i** [comment]
P.S. most dbus related will result as a desktop environment installation, which is overkill for a service based system.

**Comment by akira25** [comment]
`dbus-user-session` is a standalone package with only a few kilobytes in size. On Debian11 it has no dependencies on any desktop environment.

```sh
~$ apt info dbus-user-session
Package: dbus-user-session
Version: 1.12.24-0+deb11u1
Priority: optional
Section: admin
Source: dbus
Maintainer: Utopia Maintenance Team <pkg-utopia-maintainers@lists.alioth.debian.org>
Installed-Size: 134 kB
Provides: dbus-session-bus, default-dbus-session-bus
Depends: dbus (>= 1.12.24-0+deb11u1), libpam-systemd, systemd
Recommends: systemd-sysv
Breaks: dbus-x11 (<< 1.9.10-2~), policykit-1 (<< 0.105-12~), udisks2 (<< 2.1.5-2~)
Homepage: https://dbus.freedesktop.org/
Download-Size: 99.7 kB
APT-Manual-Installed: yes
APT-Sources: http://security.debian.org/debian-security bullseye-security/main amd64 Packages
Description: simple interprocess messaging system (systemd --user integration)
 D-Bus is a message bus, used for sending messages between applications.
 Conceptually, it fits somewhere in between raw sockets and CORBA in
 terms of complexity.
```

Therefore I think that package would be a quite neat fix for the problem. At least on Debian11 systems. For other distros I don't have information on that.

I consider this more a deployment issue, than a podman bug. Thus I though the issue would be addressed here at best.

**Comment by hswong3i** [comment]
As upstream already well discuss this issue, comment as false negative, and reduce the log level, I couldn't agree a downstream deployment override this with a dirty workaround :-(

**Comment by akira25** [comment]
I am a bit upset having this labeled as a "dirty workaround". :-(

However, as the downgrading-the-message-solution from here https://github.com/containers/podman/issues/9353#issuecomment-780470643

doesn't seem to work properly, what else do you suggest to do on that problem? Just ignoring it seems quite contradictory to the sense of a warning to me.

**Comment by hswong3i** [comment]
I comment it as dirty workaround because:
1. podman don't really need dbus, at least I had compile and using podman for more than 3 years without dbus as build dependency
2. If dbus is a must for podman, it should specify in .deb/.rpm during package building, but not dirty fix with DevOps
3. dbus (the dependency) will result as a lot of other else desktop related package, so again it is not a must

If upstream solution which reduce the log level (again) no longer functioning as expected, please open bug report to podman repo, but not here.

**Comment by hswong3i** [comment]
At least, it is about 21.4 MB, but not just 134 kB:

```
$ sudo podman run -ti --rm debian:11

root@059700937a49:/# apt update 
Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
Get:4 http://deb.debian.org/debian bullseye/main amd64 Packages [8184 kB]
Get:5 http://deb.debian.org/debian-security bullseye-security/main amd64 Packages [210 kB]
Get:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [14.6 kB]
Fetched 8616 kB in 2s (4849 kB/s)                          
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.

root@059700937a49:/# apt install dbus-user-session
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  dbus dmsetup libapparmor1 libargon2-1 libcap2 libcryptsetup12 libdbus-1-3 libdevmapper1.02.1
  libexpat1 libip4tc2 libjson-c5 libkmod2 libnss-systemd libpam-systemd systemd systemd-sysv
  systemd-timesyncd
Suggested packages:
  systemd-container policykit-1
The following NEW packages will be installed:
  dbus dbus-user-session dmsetup libapparmor1 libargon2-1 libcap2 libcryptsetup12 libdbus-1-3
  libdevmapper1.02.1 libexpat1 libip4tc2 libjson-c5 libkmod2 libnss-systemd libpam-systemd systemd
  systemd-sysv systemd-timesyncd
0 upgraded, 18 newly installed, 0 to remove and 0 not upgraded.
Need to get 6649 kB of archives.
After this operation, 21.4 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
```

BTW, if https://github.com/containers/podman/issues/9353 didn't fix nicely, please open bug report there ;-)
