### ISSUE TITLE
Podman Repo: Journald logging

### ISSUE THREAD

**Issue by djarbz** [alvistack/ansible-role-podman#18]
Hello,

I'm not sure if this is something that you can fix or not, but when attempting to use `--log-driver=journald` I get the following error.
`Error: failed to initialize journal: journald logging only enabled with systemd on linux: no support for this OS yet`
I'm wondering if it is a compile time option to enable?

This is on Debian Bullseye.

**Comment by hswong3i** [comment]
Duplicated with #9
