### ISSUE TITLE
Podman 4.0.1 Debian Rootless Port

### ISSUE THREAD

**Issue by djarbz** [alvistack/ansible-role-podman#2]
I installed Podman from your repo for Debian 11.
`podman/unknown,now 100:4.0.1-1 amd64 [installed]`

It appears that there is a Debian bug per this [issue](https://github.com/containers/podman/issues/13347).

If I understand correctly, when you compile, you need to also `make rootlessport`.

**Comment by hswong3i** [comment]
@djarbz Go catch and you are my hero, that's my miss and laziness ;-P

Originally I don't believe podman's rootless container as production ready, so always use `sudo podman` locally. For simplicity I skip all tests, docs, mans, `podman-remote`, and so also miss the newly introduced `rootlessport`, too.

Both AlviStack Podman 3.3.x, 3.4.x and 4.0.x are now rebuilding with corresponding missing `podman-remote` and `rootlessport`.

Thank you again for using this repo, and please feel free to share if you have good/bad experience with podman + rootless container (e.g. if my repo still missing some important packages or corresponding settings).

P.S. I guess you may already understand that, accordingly to the complicated packages dependencies for podman/buildah/skopeo/etc, I had manually package ALL related under single repo https://build.opensuse.org/project/show/home:alvistack. If you are going to test podman rootless container with my repo and report bugs, you need to follow my greedy ALL-OR-NOTHING policy (with package `Epoch = 100` which override any OS upstream dependency ordering). BTW, please feel free to report bugs, I will fix it ASAP, and also report corresponding PR to upstream if suitable ;-)

**Comment by djarbz** [comment]
@hswong3i I'm still getting the error, but I've narrowed it down to a specific line in my setup.

```
root@2006-ct:~# apt list podman -a
Listing... Done
podman/unknown,now 100:4.0.1-1 amd64 [installed]
podman/unknown 100:4.0.0-1 amd64
podman/unknown 100:3.4.4-1 amd64
podman/unknown 100:3.4.3-1 amd64
podman/unknown 100:3.4.2-1 amd64
podman/unknown 100:3.3.1-1 amd64
podman/unknown 100:3.3.0-1 amd64
podman/stable 3.0.1+dfsg1-3+b2 amd64
```

It appears that when I include this option `--network slirp4netns:enable_ipv6=true` that it fails with the below error.
```
Error: could not find "rootlessport" in one of [/usr/local/libexec/podman /usr/local/lib/podman /usr/libexec/podman /usr/lib/podman].  To resolve this error, set the helper_binaries_dir key in the `[engine]` section of containers.conf to the directory containing your helper binaries.
```

Would this have something to do with the networking change in Podman 4.0? It looks like it does not throw that error with your 3.4.4-1 version.

**Comment by hswong3i** [comment]
@djarbz again good catch and my bad...

I carelessly compile and install as `/usr/bin/rootlessport`, which should be install as podman plugin under `/usr/libexec/podman/rootlessport`...

Change applied to https://github.com/alvistack/containers-podman/commit/9f9c5396dce4c0f393f34fe09d5ac68324512b88#diff-889c5495b68d2a0c0d1f238818716a71939918499efbc0fc6d2994319624fc67R25-R35, it is now re-packaging with OBS.

P.S. I am always lazy on bumping the release number (i.e. from `100:4.0.1-1` to `100:4.0.1-2`)... Well I am just an unofficial packager... So please kindly run following command for reinstall, e.g.:
```
$ sudo rm -rf /var/cache/apt/archives/*
$ sudo apt-get update
$ sudo apt-get -y install --reinstall podman

$ sudo podman version
Client:       Podman Engine
Version:      4.0.1
API Version:  4.0.1
Go Version:   go1.17.7

Built:      Thu Jan  1 08:00:00 1970
OS/Arch:    linux/amd64

$ dpkg -L podman | grep rootlessport
/usr/libexec/podman/rootlessport

$ sudo podman run -ti --rm debian:10 ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0@if76: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 42:ba:58:ec:a8:fa brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.88.2.223/16 brd 10.88.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::40ba:58ff:feec:a8fa/64 scope link 
       valid_lft forever preferred_lft forever

$ sudo podman run -ti --rm --network slirp4netns:enable_ipv6=true debian:10 ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: tap0: <BROADCAST,UP,LOWER_UP> mtu 65520 qdisc fq_codel state UNKNOWN group default qlen 1000
    link/ether da:d2:76:62:ef:a5 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.100/24 brd 10.0.2.255 scope global tap0
       valid_lft forever preferred_lft forever
    inet6 fd00::d8d2:76ff:fe62:efa5/64 scope global dynamic mngtmpaddr 
       valid_lft 86400sec preferred_lft 14400sec
    inet6 fe80::d8d2:76ff:fe62:efa5/64 scope link 
       valid_lft forever preferred_lft forever
 ```

**Comment by djarbz** [comment]
Ok, looks like that is good to go, thank you for your help!
