### ISSUE TITLE
Any plan for arm64 build?

### ISSUE THREAD

**Issue by dev-techmoe** [alvistack/ansible-role-podman#22]
Hello, firstly thank you for this project.  
Seems [this repo](https://build.opensuse.org/repositories/home:alvistack/containers-podman-4.4.1) does not has the build for arm64, any plan for this? thank you.

**Comment by hswong3i** [comment]
No plan yet, see https://github.com/alvistack/ansible-collection-kubernetes/issues/8#issuecomment-1207221144
