### ISSUE TITLE
missing quadlet

### ISSUE THREAD

**Issue by hmoffatt** [alvistack/ansible-role-podman#23]
Thanks again for the up to date podman packages for Debian. I apologise that this bug isn't related to the ansible role but the podman package itself, but that repo doesn't have issues enabled and I wasn't sure where else to report this.

quadlet seems to be missing in the binary packages, although I see it in the source tree https://github.com/alvistack/containers-podman/tree/alvistack/v4.6.2/pkg/systemd/quadlet . This was added to podman in the 4.4 release I think.

**Comment by hmoffatt** [comment]
I've put in https://github.com/alvistack/containers-podman/pull/147 to add quadlet to the Debian packaging.

**Comment by hswong3i** [comment]
@hmoffatt good catch, thank you very much for your PR, too ;-)

Sorry for my miss, sometime I may simply forget `git diff Makefile` with previous version for verify...

Fix should also apply for both .deb and .rpm, a modified version goes to https://github.com/alvistack/containers-podman/commit/f3a5ffd7eca4fcd5f2b7e5aaf6f7c0023762fe7a, and should now available via https://build.opensuse.org/package/show/home:alvistack/containers-podman-4.6.2.

**Comment by hmoffatt** [comment]
Thanks for attending to this so quickly. Looks good now.
