### ISSUE TITLE
XDG_RUNTIME_DIR directory "/run/user/1000" is not owned by the current user

### ISSUE THREAD

**Issue by djarbz** [alvistack/ansible-role-podman#4]
Hello,

I have had this [ticket](https://github.com/containers/podman/issues/13338) opened with Podman for a while and they claim it has been fixed in a recent change to https://github.com/containers/common/pull/947

Can you verify that your latest build includes this change?
I updated and the issue still remains.

**Comment by hswong3i** [comment]
They commit it into main 20 days ago (2022-03-02), but the latest version https://github.com/containers/common/releases/tag/v0.47.4 released on 2022-02-10, so for sure we not yet have that fix included…

What I could do is manually include that commit into OUR 0.47.4 package as a hotfix and rebuild it.

Give me some time for a try ;-)

**Comment by djarbz** [comment]
That would be fantastic!
Thank you

**Comment by hswong3i** [comment]
At least I give a patch for both containers-common and podman (which common located as submodule so dirty patch applied).

Packages rebuilding and you may try later: https://build.opensuse.org/package/show/home:alvistack/containers-podman-4.0.2

**Comment by djarbz** [comment]
Hi @hswong3i I have not seen a new version available in APT yet.
I even tried rebuilding my host and it seems the issue is still not yet fixed.
