### ISSUE TITLE
Ensure GPG is installed

### ISSUE THREAD

**Issue by dmotte** [alvistack/ansible-role-podman#8]
Hi, first of all thanks for creating this role! 🙂 very useful

On the first attempt it failed on my system (_Debian 11_) because i didn't have the `gpg` package installed:

```
TASK [alvistack.podman : apt-key add] ******************************************
FAILED - RETRYING: [default]: apt-key add (3 retries left).
FAILED - RETRYING: [default]: apt-key add (2 retries left).
FAILED - RETRYING: [default]: apt-key add (1 retries left).
failed: [default] (item={'keyring': '/etc/apt/trusted.gpg.d/home_alvistack.gpg', 'url': 'http://downloadcontent.opensuse.org/repositories/home:/alvistack/Debian_11/Release.key', 'id': '789CFFDE0295B8A1F4E5690C4BECC97550D0B1FD', 'state': 'present'}) => {"ansible_loop_var": "item", "attempts": 3, "changed": false, "item": {"id": "789CFFDE0295B8A1F4E5690C4BECC97550D0B1FD", "keyring": "/etc/apt/trusted.gpg.d/home_alvistack.gpg", "state": "present", "url": "http://downloadcontent.opensuse.org/repositories/home:/alvistack/Debian_11/Release.key"}, "msg": "Failed to find required executable \"gpg\" in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"}
```

Installing it with `apt-get install -y gpg` solved the problem. It would be nice if the role ensures this by itself :) It is as simple as adding `gpg` to the `_apt` list here: https://github.com/alvistack/ansible-role-podman/blob/master/vars/debian-11.yml#L28

**Comment by hswong3i** [comment]
IMHO, adding `gpg` to the `_apt` list is a bit overkill:
* `gpg` should be something generally available for your daily operational system
* `ansible-role-podman` and its minimal self-provisioning on localhost with `molecule converge` is target for simplicity, but not for OS comprehensive provisioning (it should be the duty of https://github.com/alvistack/ansible-role-bootstrap)

Anyway, I always approach https://en.wikipedia.org/wiki/Unix_philosophy as https://en.wikipedia.org/wiki/Minimalism_(computing) and https://en.wikipedia.org/wiki/Modular_programming if possible (or even say https://en.wikipedia.org/wiki/KISS_principle). Although this is just a simple fix but I will not accept it, sorry and thank you for your kindly understanding.

**Comment by dmotte** [comment]
OK, I understand 😉 thanks a lot for your explanation
