### ISSUE TITLE
journald logging support

### ISSUE THREAD

**Issue by orzFly** [alvistack/ansible-role-podman#9]
needs build tag `systemd`

https://github.com/alvistack/containers-podman/blob/alvistack/v4.1.1/Makefile#L314
https://github.com/containers/podman/blob/10569c988f8ad3bfa796e52c61d7f4ef5266c193/libpod/container_log_linux.go#L2
https://github.com/containers/podman/blob/10569c988f8ad3bfa796e52c61d7f4ef5266c193/libpod/container_log_unsupported.go

**Comment by hswong3i** [comment]
@orzFly sorry for my miss, I miss this issue.

Double check that all of our supported OS could compile with `systemd` build tag, including CentOS 7 or openSUSE Leap 15.3 or Ubuntu 18.04.

So it is now newly added, see https://github.com/alvistack/containers-podman/commit/d9f05cc273189d494862c00442d844f186c89ee4#diff-889c5495b68d2a0c0d1f238818716a71939918499efbc0fc6d2994319624fc67R5-R23

After OBS complete package build you could fetch it with asked feature. Thank you for reporting.

**Comment by hswong3i** [comment]
@orzFly sorry again, the change doesn't benefit as expected, it break all of my docker image packaging by GitLab Runner + Libvirt + Vagrant + Podman.

Looks like this could only benefit if (see https://github.com/containers/conmon/issues/67):
* Both crun + conmon + podman are all with systemd journald support, AND
* We are running podman with root, but not rootless mode

So I need to revert the changes. Please kindly understand...

**Comment by orzFly** [comment]
Never mind. Thank you again for this.

Sorry to hear the breakings! I regret to not saying before, that podman defaults to journald logging if its compiled with. So there should be some changes of the default config for non-breaking upgrades.

I was planning to upgrade my podmans this weekend and try your new version, but it seemed to be late.

I do run podman as root since I use podman as a replacement for Docker. Not sure if it's possible to have crun and conmon all compiled with systemd-journald support in the future.

**Comment by hswong3i** [comment]
Seems kubic repo also try to avoid this support from my point of view. Moreover people always have more wish to replace Docker with Podman, especially in rootless mode, so root-only default compile and setup seems not a good start with good price and performance ratio :-(

**Comment by hswong3i** [comment]
@bverhagen from https://build.opensuse.org/project/show/home:alvistack#comment-1715355

> Hello,
> 
> I am using your project for installing podman, since it seems to be the only one in the Suse ecosystem to provide podman-netavark and podman-aardvark-dns already (unless you can point me to a different upstream for this?). So first of all: many thanks for this!
> 
> However, it seems that your version of podman does not support the journald log-driver. When I try to use it on microOS, I get:
> 
> journald logging only enabled with systemd on linux: no support for this OS yet
> 
> As microOS is obviously a Linux flavour, I think it is a feature toggle that is for some reason not enabled during the build? Podman in the upstream repo's seem to support this log driver. Would it be much work for you to enable this log driver?

I had try that before, but no luck and not such useful: https://github.com/alvistack/ansible-role-podman/issues/9
